### ISSUE TITLE
An error occurred during login to the console

### ISSUE THREAD

**Issue by puleiC** [douban/charts#70]
![1712828393343](https://github.com/douban/charts/assets/102528566/975d4d03-9a63-4b72-bc50-69e7c389ee5b)
INFO:root:Account 70ac5238-d66a-4c05-8c4c-0eaf5132379c logged in successfully.
ERROR:app:Exception on /console/api/login [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/app/api/controllers/console/setup.py", line 84, in decorated
    return view(*args, **kwargs)
  File "/app/api/controllers/console/auth/login.py", line 37, in post
    token = AccountService.get_account_jwt_token(account)
  File "/app/api/services/account_service.py", line 78, in get_account_jwt_token
    token = PassportService().issue(payload)
  File "/app/api/libs/passport.py", line 11, in issue
    return jwt.encode(payload, self.sk, algorithm='HS256')
  File "/usr/local/lib/python3.10/site-packages/jwt/api_jwt.py", line 73, in encode
    return api_jws.encode(
  File "/usr/local/lib/python3.10/site-packages/jwt/api_jws.py", line 160, in encode
    key = alg_obj.prepare_key(key)
  File "/usr/local/lib/python3.10/site-packages/jwt/algorithms.py", line 265, in prepare_key
    key_bytes = force_bytes(key)
  File "/usr/local/lib/python3.10/site-packages/jwt/utils.py", line 22, in force_bytes
    raise TypeError("Expected a string value")
TypeError: Expected a string value
INFO:root:Account 70ac5238-d66a-4c05-8c4c-0eaf5132379c logged in successfully.
ERROR:app:Exception on /console/api/login [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/app/api/controllers/console/setup.py", line 84, in decorated
    return view(*args, **kwargs)
  File "/app/api/controllers/console/auth/login.py", line 37, in post
    token = AccountService.get_account_jwt_token(account)
  File "/app/api/services/account_service.py", line 78, in get_account_jwt_token
    token = PassportService().issue(payload)
  File "/app/api/libs/passport.py", line 11, in issue
    return jwt.encode(payload, self.sk, algorithm='HS256')
  File "/usr/local/lib/python3.10/site-packages/jwt/api_jwt.py", line 73, in encode
    return api_jws.encode(
  File "/usr/local/lib/python3.10/site-packages/jwt/api_jws.py", line 160, in encode
    key = alg_obj.prepare_key(key)
  File "/usr/local/lib/python3.10/site-packages/jwt/algorithms.py", line 265, in prepare_key
    key_bytes = force_bytes(key)
  File "/usr/local/lib/python3.10/site-packages/jwt/utils.py", line 22, in force_bytes
    raise TypeError("Expected a string value")
TypeError: Expected a string value

**Comment by LeoQuote** [comment]
我猜你没初始化数据库, 这我可是在 wiki 里写了, 安装完了之后是要手动初始化数据库的. 

https://github.com/douban/charts/tree/master/charts/dify#install

**Comment by puleiC** [comment]
不是   是values.yaml少了  extraBackendEnvs: 
  - name: SECRET_KEY
    value: ***    我不知道这个是一个必须字段  查看了dockerfile-compose才反应过来  折腾了一天～

**Comment by LeoQuote** [comment]
好吧，解决了就好，遇到啥问题欢迎pr

**Comment by puleiC** [comment]
感谢
