### ISSUE TITLE
When using an external minio S3 bucket as storage, an error will be reported when executing db upgrade:

### ISSUE THREAD

**Issue by zibuyule** [douban/charts#85]
https://artifacthub.io/packages/helm/douban/dify

# install it
```
$ helm repo add douban https://douban.github.io/charts/
$ helm pull douban/dify 

```
APPLICATION VERSION
0.6.8

I used an external minio and executed db migration (kubectl exec -it dify-pod-name -- flask db upgrade) after installation, but an error always occurred.
The configuration in values is:
```
minio:
   embedded: false
   externalMinio:
     host: "10.23.21.6"
     port: 443
     bucket: "dify"
     verify_ssl: false
     access_key_id: "PtG4wUVhux3Euxxxxa"
     secret_access_key: "IWXi4TqLoCSrN2vKjyxxxxxxxxxo"
     iam_auth: false

```

The error is similar to:
```
root@nodedev1:/home/dothi/dify#  kubectl get all -n dify
NAME                                 READY   STATUS    RESTARTS   AGE
pod/dify-api-5ccd649c48-c78j5        1/1     Running   0          29m
pod/dify-frontend-6bc87cccbd-gsgjq   1/1     Running   0          29m
pod/dify-postgresql-0                1/1     Running   0          29m
pod/dify-redis-master-0              1/1     Running   0          29m
pod/dify-sandbox-5889544f86-jgwjw    1/1     Running   0          29m
pod/dify-worker-7c95596d7d-c2xc2     1/1     Running   0          29m

NAME                          TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
service/dify-api-svc          ClusterIP   10.234.7.23     <none>        80/TCP     29m
service/dify-frontend         ClusterIP   10.234.42.161   <none>        80/TCP     29m
service/dify-postgresql       ClusterIP   10.234.28.71    <none>        5432/TCP   29m
service/dify-postgresql-hl    ClusterIP   None            <none>        5432/TCP   29m
service/dify-redis-headless   ClusterIP   None            <none>        6379/TCP   29m
service/dify-redis-master     ClusterIP   10.234.45.20    <none>        6379/TCP   29m
service/dify-sandbox          ClusterIP   10.234.47.30    <none>        80/TCP     29m

NAME                            READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/dify-api        1/1     1            1           29m
deployment.apps/dify-frontend   1/1     1            1           29m
deployment.apps/dify-sandbox    1/1     1            1           29m
deployment.apps/dify-worker     1/1     1            1           29m

NAME                                       DESIRED   CURRENT   READY   AGE
replicaset.apps/dify-api-5ccd649c48        1         1         1       29m
replicaset.apps/dify-frontend-6bc87cccbd   1         1         1       29m
replicaset.apps/dify-sandbox-5889544f86    1         1         1       29m
replicaset.apps/dify-worker-7c95596d7d     1         1         1       29m

NAME                                 READY   AGE
statefulset.apps/dify-postgresql     1/1     29m
statefulset.apps/dify-redis-master   1/1     29m


root@nodedev1:/home/dothi/dify# kubectl exec -it dify-worker-7c95596d7d-c2xc2 -n dify -- flask db upgrade
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
2024-05-28 08:32:41.496 DEBUG [MainThread] [hooks.py:482] - Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane
2024-05-28 08:32:41.498 DEBUG [MainThread] [hooks.py:482] - Changing event name from before-call.apigateway to before-call.api-gateway
2024-05-28 08:32:41.499 DEBUG [MainThread] [hooks.py:482] - Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict
2024-05-28 08:32:41.500 DEBUG [MainThread] [hooks.py:482] - Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration
2024-05-28 08:32:41.500 DEBUG [MainThread] [hooks.py:482] - Changing event name from before-parameter-build.route53 to before-parameter-build.route-53
2024-05-28 08:32:41.501 DEBUG [MainThread] [hooks.py:482] - Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search
2024-05-28 08:32:41.501 DEBUG [MainThread] [hooks.py:482] - Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section
2024-05-28 08:32:41.504 DEBUG [MainThread] [hooks.py:482] - Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask
2024-05-28 08:32:41.504 DEBUG [MainThread] [hooks.py:482] - Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section
2024-05-28 08:32:41.504 DEBUG [MainThread] [hooks.py:482] - Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search
2024-05-28 08:32:41.504 DEBUG [MainThread] [hooks.py:482] - Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section
2024-05-28 08:32:41.510 DEBUG [MainThread] [utils.py:432] - IMDS ENDPOINT: http://169.254.169.254/
2024-05-28 08:32:41.512 DEBUG [MainThread] [credentials.py:2038] - Looking for credentials via: env
2024-05-28 08:32:41.512 DEBUG [MainThread] [credentials.py:2038] - Looking for credentials via: assume-role
2024-05-28 08:32:41.512 DEBUG [MainThread] [credentials.py:2038] - Looking for credentials via: assume-role-with-web-identity
2024-05-28 08:32:41.512 DEBUG [MainThread] [credentials.py:2038] - Looking for credentials via: sso
2024-05-28 08:32:41.512 DEBUG [MainThread] [credentials.py:2038] - Looking for credentials via: shared-credentials-file
2024-05-28 08:32:41.513 DEBUG [MainThread] [credentials.py:2038] - Looking for credentials via: custom-process
2024-05-28 08:32:41.513 DEBUG [MainThread] [credentials.py:2038] - Looking for credentials via: config-file
2024-05-28 08:32:41.513 DEBUG [MainThread] [credentials.py:2038] - Looking for credentials via: ec2-credentials-file
2024-05-28 08:32:41.513 DEBUG [MainThread] [credentials.py:2038] - Looking for credentials via: boto-config
2024-05-28 08:32:41.513 DEBUG [MainThread] [credentials.py:2038] - Looking for credentials via: container-role
2024-05-28 08:32:41.513 DEBUG [MainThread] [credentials.py:2038] - Looking for credentials via: iam-role
2024-05-28 08:32:41.514 DEBUG [MainThread] [connectionpool.py:245] - Starting new HTTP connection (1): 169.254.169.254:80
2024-05-28 08:32:42.518 DEBUG [MainThread] [utils.py:466] - Caught retryable HTTP exception while making metadata service request to http://169.254.169.254/latest/api/token: Connect timeout on endpoint URL: "http://169.254.169.254/latest/api/token"
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
  File "/usr/local/lib/python3.10/site-packages/gevent/_socketcommon.py", line 590, in connect
    self._internal_connect(address)
  File "/usr/local/lib/python3.10/site-packages/gevent/_socketcommon.py", line 640, in _internal_connect
    self._wait(self._write_event)
  File "src/gevent/_hub_primitives.py", line 317, in gevent._gevent_c_hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 322, in gevent._gevent_c_hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 313, in gevent._gevent_c_hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 314, in gevent._gevent_c_hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 55, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_waiter.py", line 154, in gevent._gevent_c_waiter.Waiter.get
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
TimeoutError: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/botocore/httpsession.py", line 464, in send
    urllib_response = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 445, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/util.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 497, in _make_request
    conn.request(
  File "/usr/local/lib/python3.10/site-packages/botocore/awsrequest.py", line 96, in request
    rval = super().request(method, url, body, headers, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 395, in request
    self.endheaders()
  File "/usr/local/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/site-packages/botocore/awsrequest.py", line 123, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.10/site-packages/botocore/awsrequest.py", line 223, in send
    return super().send(str)
  File "/usr/local/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 243, in connect
    self.sock = self._new_conn()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 212, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<botocore.awsrequest.AWSHTTPConnection object at 0x7f076392e200>, 'Connection to 169.254.169.254 timed out. (connect timeout=1)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/botocore/utils.py", line 456, in _fetch_metadata_token
    response = self._session.send(request.prepare())
  File "/usr/local/lib/python3.10/site-packages/botocore/httpsession.py", line 499, in send
    raise ConnectTimeoutError(endpoint_url=request.url, error=e)
botocore.exceptions.ConnectTimeoutError: Connect timeout on endpoint URL: "http://169.254.169.254/latest/api/token"
2024-05-28 08:32:42.523 DEBUG [MainThread] [connectionpool.py:245] - Starting new HTTP connection (2): 169.254.169.254:80
2024-05-28 08:32:43.525 DEBUG [MainThread] [utils.py:513] - Caught retryable HTTP exception while making metadata service request to http://169.254.169.254/latest/meta-data/iam/security-credentials/: Connect timeout on endpoint URL: "http://169.254.169.254/latest/meta-data/iam/security-credentials/"
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
  File "/usr/local/lib/python3.10/site-packages/gevent/_socketcommon.py", line 590, in connect
    self._internal_connect(address)
  File "/usr/local/lib/python3.10/site-packages/gevent/_socketcommon.py", line 640, in _internal_connect
    self._wait(self._write_event)
  File "src/gevent/_hub_primitives.py", line 317, in gevent._gevent_c_hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 322, in gevent._gevent_c_hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 313, in gevent._gevent_c_hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 314, in gevent._gevent_c_hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 55, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_waiter.py", line 154, in gevent._gevent_c_waiter.Waiter.get
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
TimeoutError: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/botocore/httpsession.py", line 464, in send
    urllib_response = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 445, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/util.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 497, in _make_request
    conn.request(
  File "/usr/local/lib/python3.10/site-packages/botocore/awsrequest.py", line 96, in request
    rval = super().request(method, url, body, headers, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 395, in request
    self.endheaders()
  File "/usr/local/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/site-packages/botocore/awsrequest.py", line 123, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.10/site-packages/botocore/awsrequest.py", line 223, in send
    return super().send(str)
  File "/usr/local/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 243, in connect
    self.sock = self._new_conn()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 212, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<botocore.awsrequest.AWSHTTPConnection object at 0x7f076392f4f0>, 'Connection to 169.254.169.254 timed out. (connect timeout=1)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/botocore/utils.py", line 509, in _get_request
    response = self._session.send(request.prepare())
  File "/usr/local/lib/python3.10/site-packages/botocore/httpsession.py", line 499, in send
    raise ConnectTimeoutError(endpoint_url=request.url, error=e)
botocore.exceptions.ConnectTimeoutError: Connect timeout on endpoint URL: "http://169.254.169.254/latest/meta-data/iam/security-credentials/"
2024-05-28 08:32:43.526 DEBUG [MainThread] [utils.py:599] - Max number of attempts exceeded (1) when attempting to retrieve data from metadata service.
2024-05-28 08:32:43.528 DEBUG [MainThread] [loaders.py:180] - Loading JSON file: /usr/local/lib/python3.10/site-packages/botocore/data/endpoints.json
2024-05-28 08:32:43.543 DEBUG [MainThread] [loaders.py:180] - Loading JSON file: /usr/local/lib/python3.10/site-packages/botocore/data/sdk-default-configuration.json
2024-05-28 08:32:43.543 DEBUG [MainThread] [hooks.py:238] - Event choose-service-name: calling handler <function handle_service_name_alias at 0x7f079215d2d0>
2024-05-28 08:32:43.556 DEBUG [MainThread] [loaders.py:180] - Loading JSON file: /usr/local/lib/python3.10/site-packages/botocore/data/s3/2006-03-01/service-2.json
2024-05-28 08:32:43.579 DEBUG [MainThread] [loaders.py:180] - Loading JSON file: /usr/local/lib/python3.10/site-packages/botocore/data/s3/2006-03-01/endpoint-rule-set-1.json.gz
2024-05-28 08:32:43.583 DEBUG [MainThread] [loaders.py:180] - Loading JSON file: /usr/local/lib/python3.10/site-packages/botocore/data/partitions.json
2024-05-28 08:32:43.585 DEBUG [MainThread] [hooks.py:238] - Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x7f07920c71c0>
2024-05-28 08:32:43.585 DEBUG [MainThread] [hooks.py:238] - Event creating-client-class.s3: calling handler <function lazy_call.<locals>._handler at 0x7f0763d87d00>
2024-05-28 08:32:43.598 DEBUG [MainThread] [hooks.py:238] - Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x7f07920c6f80>
2024-05-28 08:32:43.599 DEBUG [MainThread] [configprovider.py:942] - Looking for endpoint for s3 via: environment_service
2024-05-28 08:32:43.599 DEBUG [MainThread] [configprovider.py:942] - Looking for endpoint for s3 via: environment_global
2024-05-28 08:32:43.599 DEBUG [MainThread] [configprovider.py:942] - Looking for endpoint for s3 via: config_service
2024-05-28 08:32:43.599 DEBUG [MainThread] [configprovider.py:942] - Looking for endpoint for s3 via: config_global
2024-05-28 08:32:43.599 DEBUG [MainThread] [configprovider.py:958] - No configured endpoint found.
2024-05-28 08:32:43.600 DEBUG [MainThread] [endpoint.py:408] - Setting s3 timeout as (60, 60)
2024-05-28 08:32:43.602 DEBUG [MainThread] [loaders.py:180] - Loading JSON file: /usr/local/lib/python3.10/site-packages/botocore/data/_retry.json
2024-05-28 08:32:43.603 DEBUG [MainThread] [client.py:282] - Registering retry handlers for service: s3
2024-05-28 08:32:43.603 DEBUG [MainThread] [utils.py:1587] - Registering S3 region redirector handler
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 64b051264f32, init
INFO  [alembic.runtime.migration] Running upgrade 64b051264f32 -> 9f4e3427ea84, add created by role
INFO  [alembic.runtime.migration] Running upgrade 9f4e3427ea84 -> a45f4dfde53b, add language to recommend apps
INFO  [alembic.runtime.migration] Running upgrade a45f4dfde53b -> 614f77cecc48, add last active at
INFO  [alembic.runtime.migration] Running upgrade 614f77cecc48 -> e32f6ccb87c6, e08af0a69ccefbb59fa80c778efee300bb780980
INFO  [alembic.runtime.migration] Running upgrade e32f6ccb87c6 -> d3d503a3471c, add is_deleted to conversations
INFO  [alembic.runtime.migration] Running upgrade d3d503a3471c -> a5b56fb053ef, app config add speech_to_text
INFO  [alembic.runtime.migration] Running upgrade a5b56fb053ef -> 2beac44e5f5f, add is_universal in apps
INFO  [alembic.runtime.migration] Running upgrade 2beac44e5f5f -> 7ce5a52e4eee, add tool providers
INFO  [alembic.runtime.migration] Running upgrade 7ce5a52e4eee -> 8d2d099ceb74, add_qa_model_support
INFO  [alembic.runtime.migration] Running upgrade 8d2d099ceb74 -> 16fa53d9faec, add provider model support
INFO  [alembic.runtime.migration] Running upgrade 16fa53d9faec -> e35ed59becda, modify quota limit field type
INFO  [alembic.runtime.migration] Running upgrade e35ed59becda -> bf0aec5ba2cf, add provider order
INFO  [alembic.runtime.migration] Running upgrade bf0aec5ba2cf -> 5022897aaceb, add model name in embedding
INFO  [alembic.runtime.migration] Running upgrade 5022897aaceb -> 2c8af9671032, add_qa_document_language
INFO  [alembic.runtime.migration] Running upgrade 2c8af9671032 -> e8883b0148c9, add_dataset_model_name
INFO  [alembic.runtime.migration] Running upgrade e8883b0148c9 -> 853f9b9cd3b6, add message price unit
INFO  [alembic.runtime.migration] Running upgrade 853f9b9cd3b6 -> 4bcffcd64aa4, update_dataset_model_field_null_available
INFO  [alembic.runtime.migration] Running upgrade 4bcffcd64aa4 -> 6dcb43972bdc, add_dataset_retriever_resource
INFO  [alembic.runtime.migration] Running upgrade 6dcb43972bdc -> 77e83833755c, add_app_config_retriever_resource
INFO  [alembic.runtime.migration] Running upgrade 77e83833755c -> 6e2cfb077b04, add_dataset_collection_binding
INFO  [alembic.runtime.migration] Running upgrade 6e2cfb077b04 -> ab23c11305d4, add dataset query variable at app model configs.
INFO  [alembic.runtime.migration] Running upgrade ab23c11305d4 -> 2e9819ca5b28, add_tenant_id_in_api_token
INFO  [alembic.runtime.migration] Running upgrade 2e9819ca5b28 -> b3a09c049e8e, add advanced prompt templates
INFO  [alembic.runtime.migration] Running upgrade b3a09c049e8e -> 968fff4c0ab9, add_api_based_extension
INFO  [alembic.runtime.migration] Running upgrade 968fff4c0ab9 -> a9836e3baeee, add external_data_tools in app model config
INFO  [alembic.runtime.migration] Running upgrade a9836e3baeee -> 8fe468ba0ca5, add gpt4v supports
INFO  [alembic.runtime.migration] Running upgrade 8fe468ba0ca5 -> fca025d3b60f, add-dataset-retrival-model
INFO  [alembic.runtime.migration] Running upgrade fca025d3b60f -> e1901f623fd0, add-annotation-reply
INFO  [alembic.runtime.migration] Running upgrade e1901f623fd0 -> 46976cc39132, add-annotation-histoiry-score
INFO  [alembic.runtime.migration] Running upgrade 46976cc39132 -> f2a6fc85e260, add_anntation_history_message_id
INFO  [alembic.runtime.migration] Running upgrade f2a6fc85e260 -> 714aafe25d39, add_anntation_history_match_response
INFO  [alembic.runtime.migration] Running upgrade 714aafe25d39 -> 246ba09cbbdb, add_app_anntation_setting
INFO  [alembic.runtime.migration] Running upgrade 246ba09cbbdb -> 88072f0caa04, add custom config in tenant
INFO  [alembic.runtime.migration] Running upgrade 88072f0caa04 -> 187385f442fc, modify provider model name length
INFO  [alembic.runtime.migration] Running upgrade 187385f442fc -> 89c7899ca936, empty message
INFO  [alembic.runtime.migration] Running upgrade 89c7899ca936 -> 3ef9b2b6bee6, add_assistant_app
INFO  [alembic.runtime.migration] Running upgrade 3ef9b2b6bee6 -> ad472b61a054, add api provider icon
INFO  [alembic.runtime.migration] Running upgrade ad472b61a054 -> 8ec536f3c800, rename api provider credentials
INFO  [alembic.runtime.migration] Running upgrade 8ec536f3c800 -> 00bacef91f18, rename api provider description
INFO  [alembic.runtime.migration] Running upgrade 00bacef91f18 -> f25003750af4, add created/updated at
INFO  [alembic.runtime.migration] Running upgrade f25003750af4 -> c71211c8f604, add tool_invoke_model_log
INFO  [alembic.runtime.migration] Running upgrade c71211c8f604 -> 114eed84c228, remove tool id from model invoke
INFO  [alembic.runtime.migration] Running upgrade 114eed84c228 -> 4829e54d2fee, change message chain id to nullable
INFO  [alembic.runtime.migration] Running upgrade 4829e54d2fee -> 053da0c1d756, add api tool privacy
INFO  [alembic.runtime.migration] Running upgrade 053da0c1d756 -> 4823da1d26cf, add tool file
INFO  [alembic.runtime.migration] Running upgrade 4823da1d26cf -> 9fafbd60eca1, add message file belongs to
INFO  [alembic.runtime.migration] Running upgrade 9fafbd60eca1 -> 8ae9bc661daa, add tool conversation variables idx
INFO  [alembic.runtime.migration] Running upgrade 8ae9bc661daa -> 23db93619b9d, add message files into agent thought
INFO  [alembic.runtime.migration] Running upgrade 23db93619b9d -> de95f5c77138, migration serpapi_api_key
INFO  [alembic.runtime.migration] Running upgrade de95f5c77138 -> b24be59fbb04, empty message
INFO  [alembic.runtime.migration] Running upgrade b24be59fbb04 -> dfb3b7f477da, add-tool-index
INFO  [alembic.runtime.migration] Running upgrade dfb3b7f477da -> 380c6aa5a70d, add tool labels to agent thought
INFO  [alembic.runtime.migration] Running upgrade 380c6aa5a70d -> 16830a790f0f, empty message
INFO  [alembic.runtime.migration] Running upgrade 16830a790f0f -> a8f9b3c45e4a, add_tenant_id_db_index
INFO  [alembic.runtime.migration] Running upgrade a8f9b3c45e4a -> 17b5ab037c40, add-keyworg-table-storage-type
INFO  [alembic.runtime.migration] Running upgrade 17b5ab037c40 -> a8d7385a7b66, add-embeddings-provider-name
INFO  [alembic.runtime.migration] Running upgrade a8d7385a7b66 -> b289e2408ee2, add workflow
INFO  [alembic.runtime.migration] Running upgrade b289e2408ee2 -> cc04d0998d4d, set model config column nullable
INFO  [alembic.runtime.migration] Running upgrade cc04d0998d4d -> f9107f83abab, add desc for apps
INFO  [alembic.runtime.migration] Running upgrade f9107f83abab -> 42e85ed5564d, conversation columns set nullable
INFO  [alembic.runtime.migration] Running upgrade 42e85ed5564d -> b5429b71023c, messages columns set nullable
INFO  [alembic.runtime.migration] Running upgrade b5429b71023c -> 563cf8bf777b, enable tool file without conversation id
INFO  [alembic.runtime.migration] Running upgrade 563cf8bf777b -> e2eacc9a1b63, add status for message
INFO  [alembic.runtime.migration] Running upgrade e2eacc9a1b63 -> c3311b089690, add tool meta
INFO  [alembic.runtime.migration] Running upgrade c3311b089690 -> 3c7cac9521c6, add-tags-and-binding-table
INFO  [alembic.runtime.migration] Running upgrade 3c7cac9521c6 -> 47cc7df8c4f3, modify default model name length

```

I don't know if it's a problem with my configuration or something else. I used the mc command to test that this S3 bucket can be connected.
So can you help me find out what's going on? In fact, I also tried using isilon's bucket, but it still failed similarly.

**Comment by LeoQuote** [comment]
Unfortunately I cannot help you with this specific issue, I can only solve problem when you know there's something wrong with the yaml rendering, but I cannot see any clue about that.

please consult with the dify document or submit issue on their issue list.

**Comment by LeoQuote** [comment]
我刚刚发现你的 values 写的不对, 你可能被我写的 values 误导了 https://github.com/douban/charts/pull/86 我已经提了 pr 清理有误导的注释, 你可以再读读 readme , 按照 readme 进行操作.

**Comment by zibuyule** [comment]
@LeoQuote 
我的values.yaml 看起来没问题呀。如果有，请麻烦指出来。我看了很久，没看出来问题。
里面的IP确实是minio的ip地址。而且你的readme里给出的minio的例子，没有考虑过minio的地址是自定义证书的情况。


```
global:
  extraBackendEnvs:
  - name: S3_ENDPOINT
    value: "https://my-endpoint.s3.com"
  - name: S3_BUCKET_NAME
    value: "dify"
  # it is adviced to use secret to manage you sensitive info including password
  - name: S3_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: dify
        key: S3_ACCESS_KEY
  - name: S3_SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: dify
        key: S3_SECRET_KEY
```

readme里有下面的情况好像就没考虑到：
情况1：
自定义证书的情况下需要verify_ssl: false

情况2： 
像islion存储提供的S3 bucket可能不是标准的443端口。

**Comment by LeoQuote** [comment]
如果你想解决问题的话, 就把 `minio.embedded` 设置成 `true` , 然后再对照 minio chart 的填写方式开启持久化即可. 

你说的这几个问题欢迎 pr

**Comment by zibuyule** [comment]
好吧，我对minio.embedded这个东西理解不了。希望能添加下注释。
我一度以为minio.embedded=false，将会使用外部的minio；如果设置minio.embedded=true，将在安装时使用chart里自安装的ninio。

另外刚刚我修改minio.embedded=true后，再kubectl exec -it dify-worker-55c8b5fc6c-8j5vm -n dify -- flask db upgrade 执行这个操作，刚才看起来没问题了。所以谢谢了。
疑惑的是，这个时候跑到minio的存储桶里居然是空的。那db upgrade不会向这个S3 BUCKET写入东西么？
这个S3 BUCKET是做什么用的？

**Comment by LeoQuote** [comment]
这个选项和你想的是一样的, 设置 为 true 就是全包了, 设置为 false 就是需要你手动注入环境变量, 环境变量的全部配置还请参考 dify 的文档和代码, 有必要的话可以 提 issue 问他们.

当前也是有一些注释的, 欢迎pr 添加更多注释.

https://github.com/douban/charts/blob/164332b343625649e8cdae44505b0fa65174ffcd/charts/dify/values.yaml#L409-L414

里面为什么是空的, 这个我也解释不了, 不好意思我只是个 yaml 工程师, 有兴趣可以去问 dify 项目组

**Comment by zibuyule** [comment]
好吧，原来设置为minio.embedded=true，还是使用的chart里自带的minio的S3 bucket。
那就是我这个问题，其实没解决。

**Comment by LeoQuote** [comment]
可以阅读一下 readme 哦，有问题请提新issue

**Comment by zibuyule** [comment]
问题刚刚已经解决了。谢谢！
